### PR TITLE
Fix RGB colors in CustomArgument#CustomArgumentException#fromString

### LINKED ISSUE #473: CustomArgumentException fromString doesn't support rgb
### CommandAPI version

9.0.3

### Minecraft version

1.20.1

### Are you shading the CommandAPI?

Yes

### What I did

```java
public class GamemodeArgument extends CustomArgument<GameMode, String> implements IArgument {

    public GamemodeArgument() {
        super(new StringArgument(Lang.NODES_GAMEMODE.getString()), info -> {
            GameMode gm = getGamemode(info.input());
            if (gm == null) {
                throw CustomArgumentException.fromString("§x§F§F§5§1§5§1R§x§F§F§5§E§5§Eo§x§F§F§6§C§6§Cm§x§F§F§7§9§7§9u§x§F§F§8§7§8§7n§x§F§F§9§4§9§4a");
            } else {
                return gm;
            }
        });
    }
}
```

### What actually happened

It does handle the colors the wrong way.

### What should have happened

it should output rgb colors

### Server logs and CommandAPI config

no logs/errors.

### Other

_No response_

### PR DESCRIPTION
**Pull request by DerEchtePilz**
This fixes #473

### CODE REVIEW

**Comment by JorelAli** [comment]
Global changelog entry?

**Review by JorelAli — APPROVED** [review]

**Review by willkroboth — APPROVED** [review]

File: commandapi-platforms/commandapi-bukkit/commandapi-bukkit-core/src/main/java/dev/jorel/commandapi/arguments/CustomArgument.java [hunk 1]
```diff
@@ -22,6 +22,7 @@
 
 import java.io.Serializable;
 
+import net.kyori.adventure.text.TextComponent;
```
Comment (willkroboth) [inline commandapi-platforms/commandapi-bukkit/commandapi-bukkit-core/src/main/java/dev/jorel/commandapi/arguments/CustomArgument.java:25]: This import was added, but it doesn't seem to be used. I'm guessing it's just leftover from some past experiments.
```suggestion
```
